services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    init: true
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - proxy
    ports:
     - "5055:5055"

networks:
  proxy:
    external: true
