services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:latest
    ports:
      - "8881:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ALLOW_LOCAL_NETWORK=1
      - DATABASE_URL=postgres://miniflux:${MINIFLUX_DB_PASSWORD}@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=${MINIFLUX_ADMIN_PASSWORD}
    restart: unless-stopped
    networks:
      - miniflux_net

  db:
    container_name: miniflux_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=${MINIFLUX_DB_PASSWORD}
      - POSTGRES_DB=miniflux
    volumes:
      - ./config/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    restart: unless-stopped
    ports:
      - "15435:5432"
    networks:
      - miniflux_net

  # miniflux_ai:
  #   container_name: miniflux_ai
  #   image: ghcr.io/qetesh/miniflux-ai:latest
  #   volumes:
  #     - ./config.yml:/app/config.yml
  #   restart: unless-stopped
  #   depends_on:
  #     - miniflux
  #   networks:
  #     - miniflux_net

networks:
  miniflux_net:
    driver: bridge
